/** @type {import('tailwindcss').Config} */
export default {
        content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
        theme: {
          extend: {
            "colors": {
                    "inverse-surface": "#2c322a",
                    "surface-bright": "#f5fbef",
                    "on-secondary-fixed": "#1a1c1c",
                    "secondary-container": "#dcdddd",
                    "on-tertiary": "#ffffff",
                    "tertiary-container": "#f26f9d",
                    "secondary-fixed-dim": "#c6c6c7",
                    "secondary": "#5d5f5f",
                    "on-background": "#171d16",
                    "error": "#ba1a1a",
                    "on-surface": "#171d16",
                    "surface-variant": "#dee4d9",
                    "secondary-fixed": "#e2e2e2",
                    "surface-dim": "#d6dcd0",
                    "surface": "#FAFAFA",
                    "primary": "#006e1c",
                    "border-input": "#EAEAEA",
                    "surface-container-lowest": "#ffffff",
                    "inverse-primary": "#78dc77",
                    "error-container": "#ffdad6",
                    "on-primary-container": "#003c0b",
                    "tertiary": "#a63360",
                    "text-primary": "#222222",
                    "on-surface-variant": "#3f4a3c",
                    "on-tertiary-fixed-variant": "#861948",
                    "on-secondary-fixed-variant": "#454747",
                    "on-primary-fixed": "#002204",
                    "on-tertiary-container": "#690034",
                    "border-subtle": "#EEEEEE",
                    "outline": "#6f7a6b",
                    "tertiary-fixed": "#ffd9e2",
                    "on-primary": "#ffffff",
                    "tertiary-fixed-dim": "#ffb1c7",
                    "on-secondary-container": "#5f6161",
                    "on-primary-fixed-variant": "#005313",
                    "surface-tint": "#006e1c",
                    "inverse-on-surface": "#edf3e7",
                    "primary-container": "#4caf50",
                    "on-secondary": "#ffffff",
                    "primary-fixed-dim": "#78dc77",
                    "on-error-container": "#93000a",
                    "on-error": "#ffffff",
                    "background": "#f5fbef",
                    "on-tertiary-fixed": "#3e001c",
                    "text-secondary": "#777777",
                    "primary-fixed": "#94f990",
                    "surface-container": "#eaf0e4",
                    "surface-container-highest": "#dee4d9",
                    "surface-container-high": "#e4eade",
                    "outline-variant": "#becab9",
                    "surface-container-low": "#f0f6ea"
            },
            "borderRadius": {
                    "DEFAULT": "0.125rem",
                    "lg": "0.25rem",
                    "xl": "0.5rem",
                    "full": "0.75rem"
            },
            "spacing": {
                    "stack-sm": "0.75rem",
                    "margin-page": "2rem",
                    "stack-lg": "3rem",
                    "gutter": "1.5rem",
                    "stack-md": "1.5rem"
            },
            "fontFamily": {
                    "headline-md": ["Inter"],
                    "headline-lg": ["Inter"],
                    "body-sm": ["Inter"],
                    "body-md": ["Inter"],
                    "body-lg": ["Inter"],
                    "label-md": ["Inter"],
                    "button": ["Inter"],
                    "headline-sm": ["Inter"]
            },
            "fontSize": {
                    "headline-md": ["24px", {"lineHeight": "1.3", "fontWeight": "300"}],
                    "headline-lg": ["32px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "300"}],
                    "body-sm": ["14px", {"lineHeight": "1.5", "fontWeight": "400"}],
                    "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
                    "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
                    "label-md": ["14px", {"lineHeight": "1.2", "letterSpacing": "0.05em", "fontWeight": "500"}],
                    "button": ["16px", {"lineHeight": "1.2", "fontWeight": "500"}],
                    "headline-sm": ["20px", {"lineHeight": "1.4", "fontWeight": "400"}]
            }
          },
        },
      }
